### ISSUE TITLE
apache_ssl_16.sh fails to complete successfully on Amazon LightSail

### ISSUE THREAD

**Issue by bstamps** [cheinle/metaLIMS#14]
Hello - I'm having issues completing the SSL certificate script with the following failure. 

```
-bash: apache_ssl_16.sh: line 55: syntax error near unexpected to
ken `('
-bash: apache_ssl_16.sh: line 55: `                <FilesMatch "\
.(cgi|shtml|phtml|php)$">'
```

That occurs after RSA key generation and after the second request for an email address.

**Comment by cheinle** [comment]
Hi bstamps -It may be that there was some error when pasting in the commands into your bash script. Is it possible you can either attach the apache_ssl_16.sh file you have or take a screenshot of these lines inside?  

Kind regards,

Cassie

**Comment by bstamps** [comment]
Absolutely- here's the attached image of the code around line 55 within vi. 

Best, 

Blake

![line55_grab](https://cloud.githubusercontent.com/assets/2664366/25391577/c615d7ec-2993-11e7-89ef-8b8d580ad194.jpeg)

**Comment by bstamps** [comment]
To update- 

Removing the offending () from line 55 allows the script to complete successfully. This appears to be an issue with bash/dash and that style of syntax, or at least in my attempts to google the issue that's what it might be.

**Comment by cheinle** [comment]
Hi  Blake, 

Apologies for the slow response.  Thanks for your update. I looks like it was a problem with my use of double quotes inside a double quoted echo statement. I have updated the file so line should look like:

![image](https://cloud.githubusercontent.com/assets/10081573/25515341/7d5c6ffe-2c16-11e7-8336-2b151f917235.png)

For the offending lines.

It sounds like you were already able to fix the problem. However if you feel comfortable, check the /etc/apache2/sites-available/default-ssl.conf file and check to make sure the line looks like 

`<FilesMatch "\.(cgi|shtml|phtml|php)$">`

Let me know how things are going and if there's anything else I can do to help.

Kind regards,

Cassie
